/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_unb_unbiquitous_jni_ZbarJni */

#ifndef _Included_br_unb_unbiquitous_jni_ZbarJni
#define _Included_br_unb_unbiquitous_jni_ZbarJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_unb_unbiquitous_jni_ZbarJni
 * Method:    decode
 * Signature: (II[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_unb_unbiquitous_jni_ZbarJni_decode
  (JNIEnv *, jobject, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
